[package]
name = "io_core"
version = "0.5.2"
license = "MIT OR Apache-2.0"
edition = "2024"
repository = "https://github.com/GrayJack/io_core"
readme = "README.md"
description = "A no_std I/O foundation for Rust."
categories = ["data-structures", "no-std"]
keywords = ["no_std", "io"]
exclude = ["todo.md"]

[package.metadata.docs.rs]
features = ["std", "nightly"]

[dependencies]
memchr = { version = "2.8.0", default-features = false }

[target.'cfg(not(all(windows, target_env = "msvc")))'.dependencies]
libc = { version = "0.2.185", default-features = false, features = [] }

[features]
default = []
alloc = []
# use nightly features
nightly = []

# Not complete, do not use it
std = ["alloc"]

# Whether to use [MaybeUninit<T>]::write_default or our own function.
__write_default = []
